---
Name: elemental
---

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'elemental/css/elemental-admin.css'
  extensions:
    - DNADesign\Elemental\Extensions\LeftAndMainElementIconsExtension
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalContentControllerExtension
  url_handlers:
    'element/$ID!': 'handleElement'
SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - 'DNADesign\Elemental\Extensions\GridFieldDetailFormItemRequestExtension'
